# Generated by Django 5.2.9 on 2025-12-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('TRANSFER', 'Transferencia')], max_length=20)),
                ('entity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('ambulance', models.CharField(choices=[('CM1', 'CM1'), ('CM2', 'CM2'), ('CM3', 'CM3'), ('S56', 'S56')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Ventilacion & Monitor', 'Ventilacion & Monitor'), ('Equipo / Vitales', 'Equipo / Vitales'), ('Bulto de trauma', 'Bulto de trauma'), ('Entubación', 'Entubación')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Entubación', 'Entubación'), ('Equipo', 'Equipo')], default='Misceláneos', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='unidades', max_length=50)),
                ('location', models.CharField(default='Almacén', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('paramedic', models.CharField(max_length=100)),
                ('ambulance', models.CharField(max_length=50)),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('medicine', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ambulance', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=20)),
                ('firma_staff1', models.TextField(blank=True, null=True)),
                ('staff2', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_staff2', models.TextField(blank=True, null=True)),
                ('millage', models.IntegerField(default=0)),
                ('combustible', models.CharField(choices=[('Full', 'Full'), ('3/4', '3/4'), ('1/2', '1/2'), ('1/4', '1/4'), ('Empty', 'Empty')], default='Full', max_length=10)),
                ('oxigeno_m', models.IntegerField(default=0)),
                ('oxigeno_d', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('seccion_vehiculo', models.JSONField(default=dict)),
                ('seccion_medical_equipment', models.JSONField(default=dict)),
                ('seccion_inmovilizacion', models.JSONField(default=dict)),
                ('seccion_canalizacion', models.JSONField(default=dict)),
                ('seccion_oxigeno_airway', models.JSONField(default=dict)),
                ('seccion_medicamentos', models.JSONField(default=dict)),
                ('seccion_miscelaneos', models.JSONField(default=dict)),
                ('seccion_entubacion', models.JSONField(default=dict)),
                ('seccion_equipo', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'ambulance', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paramedic', models.CharField(max_length=100)),
                ('ambulance', models.CharField(choices=[('CM1', 'CM1'), ('CM2', 'CM2'), ('CM3', 'CM3'), ('S56', 'S56')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('recommended_quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
            options={
                'db_table': 'recommended_inventory',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(default='Almacén', max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.inventoryitem')),
            ],
        ),
    ]
