# Generated by Django 5.2.9 on 2025-12-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceinventory',
            name='ambulance',
            field=models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('F13', 'F13'), ('F14', 'F14'), ('F15', 'F15'), ('F16', 'F16'), ('F17', 'F17')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ambulanceinventory',
            name='category',
            field=models.CharField(blank=True, choices=[('Inmovilización', 'Inmovilización'), ('Canalización', 'Canalización'), ('Airway / Oxígeno', 'Airway / Oxígeno'), ('Medicamentos', 'Medicamentos'), ('Misceláneos', 'Misceláneos'), ('Equipo / Vitales', 'Equipo / Vitales'), ('Entubación', 'Entubación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancerequisition',
            name='ambulance',
            field=models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('F13', 'F13'), ('F14', 'F14'), ('F15', 'F15'), ('F16', 'F16'), ('F17', 'F17')], max_length=10),
        ),
    ]
